import { describe, expect, it } from "vitest";
import {
	buildSteeringMessage,
	createSteeringState,
	crossedRungs,
	observePendingSteering,
	pendingSummary,
	resetSteering,
} from "../lib/steering.ts";
import type { SteeringOptions } from "../lib/steering.ts";
import {
	createRuntimeState,
	recordContextToolCallIds,
	recordPending,
	recordReplacement,
} from "../lib/runtime-state.js";

const LONG = "x".repeat(2000); // filler content; token counts are passed explicitly

const OPTS: SteeringOptions = { firstRungTokens: 5000, enabled: true };
const DISABLED: SteeringOptions = { ...OPTS, enabled: false };

describe("createSteeringState", () => {
	it("starts at level 0", () => {
		const s = createSteeringState();
		expect(s.level).toBe(0);
	});
});

describe("resetSteering", () => {
	it("resets the level in place", () => {
		const s = createSteeringState();
		s.level = 4;
		resetSteering(s);
		expect(s.level).toBe(0);
		// mutates the same object (no re-allocation)
		expect(s).toBe(s);
	});
});

describe("crossedRungs", () => {
	it("crosses nothing at or below the first rung (strict comparison)", () => {
		expect(crossedRungs(0, 5000)).toBe(0);
		expect(crossedRungs(4000, 5000)).toBe(0);
		// S == a rung does not cross it.
		expect(crossedRungs(5000, 5000)).toBe(0);
	});

	it("counts default-ladder rungs strictly below S", () => {
		// Default rungs: 5000, 8000, 13000, 21000, 34000, 55000, 89000, ...
		expect(crossedRungs(5001, 5000)).toBe(1);
		expect(crossedRungs(6000, 5000)).toBe(1);
		expect(crossedRungs(7999, 5000)).toBe(1);
		expect(crossedRungs(8000, 5000)).toBe(1); // == rung(2): still 1
		expect(crossedRungs(8001, 5000)).toBe(2);
		expect(crossedRungs(13000, 5000)).toBe(2);
		expect(crossedRungs(21000, 5000)).toBe(3);
		expect(crossedRungs(34000, 5000)).toBe(4);
		expect(crossedRungs(55000, 5000)).toBe(5);
		expect(crossedRungs(89000, 5000)).toBe(6);
	});

	it("scales with the first rung (10000: 10000, 16000, 26000, 42000, 68000, ...)", () => {
		expect(crossedRungs(10000, 10000)).toBe(0);
		expect(crossedRungs(10001, 10000)).toBe(1);
		expect(crossedRungs(16000, 10000)).toBe(1);
		expect(crossedRungs(26000, 10000)).toBe(2);
		expect(crossedRungs(42000, 10000)).toBe(3);
		expect(crossedRungs(68000, 10000)).toBe(4);
	});

	it("crosses a huge mass across many rungs (iteration terminates)", () => {
		// Enough mass to cross well past the hand-checked prefix: the rungs
		// generated by iteration must stay on the Fibonacci multipliers.
		// 1_000_000 / 5000 = 200 -> rungs below: 5000, 8000, 13000, 21000,
		// 34000, 55000, 89000, 144000, 233000, 377000, 610000, 987000.
		expect(crossedRungs(1_000_000, 5000)).toBe(12);
	});
});

describe("pendingSummary — context-event eligibility", () => {
	it("collects pending entries whose ids are in the last context event", () => {
		const rt = createRuntimeState();
		recordPending(rt, "a", 100, LONG);
		recordPending(rt, "b", 250, LONG);
		recordContextToolCallIds(rt, ["a", "b"]);
		const summary = pendingSummary(rt);
		expect(summary.items).toEqual([
			{ id: "a", tokens: 100 },
			{ id: "b", tokens: 250 },
		]);
		expect(summary.totalTokens).toBe(350);
	});

	it("excludes replaced entries even when still in the messages", () => {
		const rt = createRuntimeState();
		recordPending(rt, "a", 100, LONG);
		recordPending(rt, "b", 250, LONG);
		recordReplacement(rt, "a", "short", 1);
		recordContextToolCallIds(rt, ["a", "b"]);
		const summary = pendingSummary(rt);
		expect(summary.items).toEqual([{ id: "b", tokens: 250 }]);
		expect(summary.totalTokens).toBe(250);
	});

	it("excludes entries not in the most recent context event (marked this turn, or compacted away)", () => {
		const rt = createRuntimeState();
		recordPending(rt, "seen", 400, LONG);
		recordPending(rt, "fresh-this-turn", 300, LONG);
		recordPending(rt, "compacted-away", 200, LONG);
		// Only "seen" is in the messages the model most recently received.
		recordContextToolCallIds(rt, ["seen"]);
		const summary = pendingSummary(rt);
		expect(summary.items).toEqual([{ id: "seen", tokens: 400 }]);
		expect(summary.totalTokens).toBe(400);
	});

	it("tracks only the most recent context event (later events replace the id set)", () => {
		const rt = createRuntimeState();
		recordPending(rt, "old", 500, LONG);
		recordPending(rt, "new", 700, LONG);
		recordContextToolCallIds(rt, ["old"]);
		recordContextToolCallIds(rt, ["new"]);
		const summary = pendingSummary(rt);
		expect(summary.items).toEqual([{ id: "new", tokens: 700 }]);
		expect(summary.totalTokens).toBe(700);
	});

	it("is empty when no context event has fired yet", () => {
		const rt = createRuntimeState();
		recordPending(rt, "a", 100, LONG);
		expect(pendingSummary(rt)).toEqual({ items: [], totalTokens: 0 });
	});
});

describe("observePendingSteering — the ratchet", () => {
	it("does not fire when disabled, and does not track level", () => {
		const s = createSteeringState();
		expect(observePendingSteering(s, 90000, DISABLED)).toEqual({ fire: false });
		expect(s.level).toBe(0);
	});

	it("does not fire while the mass is at or below a rung (strict)", () => {
		const s = createSteeringState();
		expect(observePendingSteering(s, 0, OPTS).fire).toBe(false);
		expect(observePendingSteering(s, 4000, OPTS).fire).toBe(false);
		// S == the first rung: not crossed.
		expect(observePendingSteering(s, 5000, OPTS).fire).toBe(false);
		expect(s.level).toBe(0);
	});

	it("walks the worked-example ladder one rung at a time", () => {
		// Worked examples (defaults): successive turn_end masses ->
		// action, level after.
		const s = createSteeringState();
		const see = (S: number) => observePendingSteering(s, S, OPTS);
		expect(see(4000).fire).toBe(false); // level 0
		expect(see(5000).fire).toBe(false); // S == rung: level 0
		const t1 = see(6000); // rung(1) = 5000 < 6000
		expect(t1.fire).toBe(true);
		expect(s.level).toBe(1);
		expect(see(9000).fire).toBe(true); // rung(2) = 8000
		expect(s.level).toBe(2);
		expect(see(14000).fire).toBe(true); // rung(3) = 13000
		expect(s.level).toBe(3);
		expect(see(22000).fire).toBe(true); // rung(4) = 21000
		expect(s.level).toBe(4);
		expect(see(22000).fire).toBe(false); // unchanged mass: level 4
		expect(s.level).toBe(4);
		// Partial replacement drops the mass below announced rungs:
		// re-arm, no nag.
		expect(see(3000).fire).toBe(false);
		expect(s.level).toBe(0);
		// Re-grown pile is nagged again.
		expect(see(6000).fire).toBe(true);
		expect(s.level).toBe(1);
	});

	it("fires ONE nag on a multi-rung jump", () => {
		const s = createSteeringState();
		expect(observePendingSteering(s, 30000, OPTS).fire).toBe(true); // crossed 4
		expect(s.level).toBe(4);
		expect(observePendingSteering(s, 31000, OPTS).fire).toBe(false); // latched at 4
		expect(observePendingSteering(s, 35000, OPTS).fire).toBe(true); // crossed 5
		expect(s.level).toBe(5);
	});

	it("re-arms down through a partial replacement without nagging, then nags on regrowth", () => {
		const s = createSteeringState();
		observePendingSteering(s, 25000, OPTS); // crossed 4 -> level 4
		expect(s.level).toBe(4);
		// The model replaces some: S = 9000 -> crossed 2 < level 4 -> re-arm, no nag.
		expect(observePendingSteering(s, 9000, OPTS).fire).toBe(false);
		expect(s.level).toBe(2);
		// Later the pile re-grows: crossed 3 > 2 -> nag.
		expect(observePendingSteering(s, 14000, OPTS).fire).toBe(true);
		expect(s.level).toBe(3);
	});

	it("respects a custom first rung", () => {
		const s = createSteeringState();
		const opts: SteeringOptions = { ...OPTS, firstRungTokens: 10000 };
		expect(observePendingSteering(s, 10000, opts).fire).toBe(false); // == rung(1)
		expect(s.level).toBe(0);
		// 16000 has crossed rung(1) = 10000 (strictly below) — fire once.
		expect(observePendingSteering(s, 16000, opts).fire).toBe(true);
		expect(s.level).toBe(1);
		// S == rung(2) = 16000 does not cross rung(2): level holds.
		expect(observePendingSteering(s, 16000, opts).fire).toBe(false);
		expect(observePendingSteering(s, 16001, opts).fire).toBe(true); // crossed 2
		expect(s.level).toBe(2);
	});
});

describe("buildSteeringMessage", () => {
	it("mentions the count, the total, the anti-hoarding rule, and the replace tool", () => {
		const msg = buildSteeringMessage(
			3,
			4200,
			[
				{ id: "a", tokens: 3000 },
				{ id: "b", tokens: 1000 },
				{ id: "c", tokens: 200 },
			],
		);
		expect(msg).toContain("3 tool-result-pending-replacements");
		expect(msg).toContain("~4200 estimated tokens");
		expect(msg).toContain("replace_tool_result");
		expect(msg).toContain("just in case");
	});

	it("lists each pending id with its size on its own line", () => {
		const msg = buildSteeringMessage(2, 1100, [
			{ id: "id-1", tokens: 1000 },
			{ id: "id-2", tokens: 100 },
		]);
		expect(msg).toContain("- id-1 (~1000 tokens)");
		expect(msg).toContain("- id-2 (~100 tokens)");
		expect(msg.indexOf("- id-1")).toBeLessThan(msg.indexOf("- id-2"));
	});

	it("ends with the id list", () => {
		const msg = buildSteeringMessage(1, 30000, [{ id: "solo", tokens: 30000 }]);
		expect(msg.trimEnd().endsWith("- solo (~30000 tokens)")).toBe(true);
	});
});